# Generated by Django 5.2 on 2025-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('star', models.IntegerField(choices=[(1, 'Tourist'), (2, 'Standart'), (3, 'Comfort'), (4, 'First Class'), (5, 'Luxury')], default=0)),
                ('num_rooms', models.IntegerField(verbose_name='number of rooms')),
                ('services', models.TextField()),
            ],
        ),
    ]
