# Generated by Django 5.2 on 2025-05-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1.0'), (2, '2.0'), (3, '3.0'), (4, '4.0'), (5, '5.0'), (6, '6.0'), (7, '7.0'), (8, '8.0'), (9, '9.0'), (10, '10')], default=-2024),
            preserve_default=False,
        ),
    ]
