# Generated by Django 5.2 on 2025-05-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_roomattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=-2016, max_digits=10),
            preserve_default=False,
        ),
    ]
